package com.sigemp.gestion.client.gui.sis_config.form;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * NewJPanel.java
 *
 * Created on 12/06/2009, 11:47:15
 */
import com.sigemp.gestion.client.gui.component.SgImage;
import com.sigemp.gestion.client.gui.component.base.SgDialog;
import com.sigemp.gestion.constants.Comprobante;
import com.sigemp.gestion.constants.Sistema;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author cristiane
 */
public class DialogSeleccionComprobantes extends SgDialog {

    private static final Logger LOG = Logger.getLogger(DialogSeleccionComprobantes.class.getName());

    protected boolean confirmed = false;
    private final DefaultListModel<Comprobante> model = new DefaultListModel<>();

    ;

    /**
     * Get the value of confirmed
     *
     * @return the value of confirmed
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * Set the value of confirmed
     *
     * @param confirmed new value of confirmed
     */
    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * Creates new form Beneficiarios
     *
     * @param parent
     * @param modal
     */
    public DialogSeleccionComprobantes(JDialog parent, boolean modal) {
        super(parent, modal);

        initComponents();

        jb_aceptar.setIcon(SgImage.ACEPTAR.getImage(SgImage.SIZES.S16));
        jb_cancelar.setIcon(SgImage.CANCELAR.getImage(SgImage.SIZES.S16));
        
        setSize(415, 350);
        jList1.setModel(model);
        jList1.setCellRenderer(new ListadosRender());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jb_aceptar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setModal(true);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo Comprobantes:");
        jLabel6.setPreferredSize(new java.awt.Dimension(91, 20));

        jScrollPane1.setViewportView(jList1);

        jb_aceptar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jb_aceptar.setText("Aceptar");
        jb_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aceptarActionPerformed(evt);
            }
        });

        jb_cancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jb_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jb_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_aceptar)
                    .addComponent(jb_cancelar))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aceptarActionPerformed
        setConfirmed(true);
        setVisible(false);
    }//GEN-LAST:event_jb_aceptarActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jb_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<Comprobante> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_aceptar;
    private javax.swing.JButton jb_cancelar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the currentRecord
     */
    public List<Comprobante> getCurrentRecord() {
        int[] indexs = jList1.getSelectedIndices();
        List<Comprobante> ls = new ArrayList<>();
        for (Integer x : indexs) {
            ls.add(model.get(x));
        }
        return ls;
    }

    public void setTCTC(List<Comprobante> comprobantesSeleccionados, List<Comprobante> disponibles) {

        for (Comprobante tc : disponibles) {
            // Si tipo de comprobante tc esta en los que ya se encuentra, no lo muestro como opcion 
            if (comprobantesSeleccionados.contains(tc)) {
                continue;
            }
            model.addElement(tc);
        }
    }

}
