/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sigemp.gestion.client.inicio;

import com.formdev.flatlaf.FlatDarkLaf;
import com.sigemp.gestion.client.gui.component.SgImage;
import com.sigemp.gestion.client.gui.component.base.LoginForm;
import com.sigemp.gestion.client.gui.component.base.Pantallas;
import com.sigemp.gestion.client.gui.component.base.SgStatusBar;
import com.sigemp.common.FW;
import com.sigemp.gestion.constants.Sistema;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author cristian
 */
public class MainIntro extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(MainIntro.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MainIntro() {

        setIconImage(SgImage.LOGO_EMPRESA.getImage(SgImage.SIZES.S64).getImage());

        initComponents();

        SgStatusBar sgStatusBar = new SgStatusBar();
        jPanel1.add(sgStatusBar.getContainer(), BorderLayout.AFTER_LAST_LINE);

        jDesktopPane.addContainerListener(sgStatusBar);

        setPreferredSize(new Dimension(800, 600));
        pack();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                appAskClose();
            }

            @Override
            public void windowOpened(WindowEvent e) {
                // Me Conecto con la Base de datos
                appConnect();
            }

        });

        LOG.info("Constructor");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(0, 24));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
////        try {
////            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
////        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(MainIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }

        FlatDarkLaf.install();
        // Arranco la Pantalla Principal
        SwingUtilities.invokeLater(() -> {
            new MainIntro().setVisible(true);
        });

    }

    private void appAskClose() {
        int i = JOptionPane.showConfirmDialog(this, "Esta seguro de Abandonar la Aplicacion", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void appClose() {
        System.exit(0);
    }

    private void appConnect() {
        LoginForm lf = new LoginForm(this);
        lf.setVisible(true);
        if (!lf.isAccepted()) {
            appClose();
        }
        LOG.info("Iniciando menus");
        if (jMenuBar1 == null || jDesktopPane == null) {
            LOG.info("Son null");
        }

        // Cargo los Menus.
        new LoadMenu(jMenuBar1, jDesktopPane).start();

    }

    /**
     * Carga los Menus Dinamicamente
     */
    class LoadMenu extends Thread {

        JMenuBar menuBar;
        private final JDesktopPane dp;

        LoadMenu(JMenuBar menuBar, JDesktopPane dp) {
            this.menuBar = menuBar;
            this.dp = dp;
        }

        public void cargarmenus() {

            for (Pantallas p : Pantallas.values()) {
                JMenu menuGrupo = getGrupo(p.getSistema(), p.getPantallaGrupo());

                JMenuItem menuItem = new JMenuItem(p.getDescripcion());
                menuItem.addActionListener((ActionEvent e) -> {
                    FW.start(dp,p);
                });
                menuGrupo.add(menuItem);

            }
            menuBar.updateUI();
        }

        @Override
        public void run() {
            cargarmenus();
        }

        /**
         * Retorno el grupo al que pertenece la pantalla. si no existe, lo crea
         *
         *
         * @param sistema
         * @param grupo
         * @return
         */
        private JMenu getGrupo(Sistema sistema, Pantallas.PantallaGrupo grupo) {
            for (int i = 0; i < menuBar.getMenuCount(); i++) {
                JMenu menuSistema = menuBar.getMenu(i);
                if (menuSistema.getText().equals(sistema.getDescripcion())) {
                    for (int k = 0; k < menuSistema.getMenuComponentCount(); k++) {
                        Component menuGrupo = menuSistema.getMenuComponent(k);
                        if (menuGrupo instanceof JMenu) {
                            JMenu jMenuGrupo = (JMenu) menuGrupo;
                            if (jMenuGrupo.getText().equals(grupo.getDes())) {
                                return jMenuGrupo;
                            }

                        }
                    }
                    JMenu nnMenuGrupo = new JMenu(grupo.getDes());
                    menuSistema.add(nnMenuGrupo);
                    return nnMenuGrupo;
                }

            }
            JMenu nMenuSistema = new JMenu(sistema.getDescripcion());
            JMenu nGrupo = new JMenu(grupo.getDes());
            menuBar.add(nMenuSistema);
            nMenuSistema.add(nGrupo);
            return nGrupo;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
